# Generated by Django 6.0.4 on 2026-05-13 00:40

import main.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Dataset name', max_length=255)),
                ('file', models.FileField(help_text='Uploaded file (CSV or Excel)', storage=main.models.DatasetStorage(), upload_to='datasets/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], help_text='Type of uploaded file', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when dataset was created')),
                ('rows_count', models.IntegerField(default=0, help_text='Number of rows in the dataset')),
                ('user', models.ForeignKey(help_text='User who owns this dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'dataset',
                'ordering': ['-created_at'],
            },
        ),
    ]
